# Generated by Django 4.1.4 on 2022-12-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_client_user_alter_notary_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=280)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('event_type', models.CharField(choices=[('AP', 'Appointment'), ('DL', 'Deadline'), ('OT', 'Other')], default='OT', max_length=2)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client')),
                ('notary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.notary')),
            ],
        ),
    ]
