# Generated by Django 4.1.4 on 2022-12-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
